name: Python test
run-name:  Run Python file

on:
  workflow_dispatch:


jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Run Python file
        run:  python3 ./workflows/app.py
